dist: trusty
language: c
dist: trusty
compiler:
    - gcc
env:
    global:
        - TRAVIS_PAR_MAKE="-j 4"
        - FI_LOG_LEVEL=warn
        - SHMEM_INFO=1
os:
    - linux

addons:
    apt:
        packages:
            - gfortran

before_install:
    - mkdir $HOME/travis
    - mkdir $HOME/travis/build
    - mkdir $HOME/travis/install
    - export SOS_SRC=$PWD
    - cd $HOME/travis
    - wget https://raw.githubusercontent.com/Sandia-OpenSHMEM/SOS/master/scripts/simple-build-ofi.sh
    - chmod +x simple-build-ofi.sh
    - export SOS_VERSION="master"
    - ./simple-build-ofi.sh $HOME/travis/build $HOME/travis/install

install:
    - cd $SOS_SRC
    - ./autogen.sh

script:
    - export PATH=$HOME/travis/install/bin:$PATH
    - cd $SOS_SRC
    - mkdir build
    - cd build
      # Note: With gcc 4.8 in Ubuntu Trusty, pthreads configury doesn't seem to
      # detect the need for -lpthread.
    - ../configure CC=oshcc CXX=oshc++ FC=oshfort CFLAGS="-std=gnu99" FCFLAGS="-fcray-pointer" LDFLAGS="-lpthread" --disable-c11-checks
    - make $TRAVIS_PAR_MAKE
    - make check
    - make distclean
    - ../configure CC=oshcc CXX=oshc++ FC=oshfort FCFLAGS="-fcray-pointer" LDFLAGS="-lpthread"
    - make $TRAVIS_PAR_MAKE
    - make check
